name: meettime
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  path_provider: ^2.1.5
  provider: ^6.1.4
  permission_handler: ^11.3.1
  flutter_app_info: ^3.0.3
  timezone: ^0.10.0
  google_fonts: ^6.2.1
  page_transition: ^2.1.0
  lottie: ^3.1.3
  google_nav_bar: ^5.0.7
  line_icons: ^2.0.3
  flutter_svg: ^2.1.0
  intl: ^0.20.2
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1
  flutter_markdown: ^0.7.7
  flutter_gemini: ^3.0.0
  animated_text_kit: ^4.2.3
  google_generative_ai: ^0.4.7
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animation/
    - assets/img/

icons_launcher:
  image_path: "assets/img/app_icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
